### ISSUE TITLE
TODO for 1.1 and 1.2

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/mios#10]
Though the purpose of 1.0 is to translate the codes in the paper (Eén, Niklas, and Niklas Sörensson. "_An extensible SAT-solver_." Theory and applications of satisfiability testing. Springer Berlin Heidelberg, 2003.) and some parts from [MiniSat 1.14](https://github.com/shnarazk/minisat114) into a program written in Haskell, I found there are a lot of differences between the paper and MiniSat 1.14; version 1.14 is not close to the paper but to [MiniSat 2.2](https://github.com/shnarazk/minisat). It makes difficult to develop mios further; most part of the solver core should be updated.
So stopping to improve the performance of the current mios 1.0.X based on the paper, I decided to switch the reference code to MiniSat 2.2 after the release of 1.0.3.
- mios 1.0 is a study on the paper.
- mios 1.1 is a study based on [MiniSat 2.2](https://github.com/shnarazk/minisat). This is the current branch [M22](https://github.com/shnarazk/mios/tree/M22) and a one month sprint I hope.

It is a shorter way to archive an expected high-performance SAT solver in Haskell.

---
#### random note
- [x] reorder functions
- [ ] GClause for binary clauses
- [x] `analyzeRemovable` and 3 variables for `analyze` family
- [ ] current target is not simp but core
- [x] var heap is ready
- [ ] Luby is ready
- [ ] LBD is ready
- [x] write the output to a file in DIMACS CNF format

**Comment by shnarazk** [comment]
## memo
- bit encoding for literal/var
- lightweight stack implementation
- change naming policy
- vector-based operations for Stack/Queue/Clause
- `litRedundant`
- now you can use mios in ghci
- single stack (no more `propQ` queue)

**Comment by shnarazk** [comment]
![screenshot from 2016-03-13 15-10-50](https://cloud.githubusercontent.com/assets/997855/13727232/dc505f52-e92d-11e5-80f8-aa86754acc9c.png)
