### ISSUE TITLE
TODO for 1.2

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/mios#17]
It deserves to release.
- [x] validity (soundness) checking by SR15m131
- [x] delete a lot of working branches
- [x] validator should display filename
- [x] replace `ClauseManager` with `WatcherList`; or rename to a better name
- [ ] delete useless comments
- [x] redo glucose (single thread) benchmark
- [ ] update documents
- [ ] release by June ~~24~~ 27

**Comment by shnarazk** [comment]
![cactus2015-su](https://cloud.githubusercontent.com/assets/997855/16031046/0d5b6f7c-3232-11e6-9a28-8c3c346faa6f.png)

**Comment by shnarazk** [comment]
![cactus2015](https://cloud.githubusercontent.com/assets/997855/16031233/cba955ba-3233-11e6-92d7-577b8e4f796d.png)

**Comment by shnarazk** [comment]
![cactus2015](https://cloud.githubusercontent.com/assets/997855/16328422/f1597c5c-3a14-11e6-8ef3-907d44831b60.png)

**Comment by shnarazk** [comment]
## the graph

![cactus2015](https://cloud.githubusercontent.com/assets/997855/16362274/62dd40da-3be5-11e6-9a90-688909618894.png)
![cactus2015-su](https://cloud.githubusercontent.com/assets/997855/16362293/07141016-3be6-11e6-9620-6a246ffd6a61.png)

**Comment by shnarazk** [comment]
### version 1.2 without Random and Criterion

![mios2](https://cloud.githubusercontent.com/assets/997855/16367598/2c647ae8-3c60-11e6-8972-f5904005c957.png)

### version 1.1 with Random for random decision selector

![mios](https://cloud.githubusercontent.com/assets/997855/16367600/316ba1c4-3c60-11e6-9735-8500d889c335.png)

**Comment by shnarazk** [comment]
![cactus2015](https://cloud.githubusercontent.com/assets/997855/16403150/375f4aea-3d2d-11e6-9683-74f30bea975e.png)
