### ISSUE TITLE
TODO for 1.0.2

### ISSUE THREAD

**Issue by shnarazk** [shnarazk/mios#5]
**Feature:**  a bug fix on DIMACS reader  + the following micro tunings (or code-cleanup) from nowrap-with-inline branch
- [x] change `level`, `activities`, `reason` and `seen` to **var-indexed** (1-based) vectors
- [x] add more type declarations
- [x] no heap for var selection
## release procedure
- [x] :mag: Implemenation Validation by _Feb. 21_.
  - [x] :school: on UF250 with mios
  - [x] on UF250 with sih4
  - [x] :church: on SAT-Race 2015 subsets with mios
  - [x] on SAT-Race 2015 subsets with sih4
- [x] :watch: Performance Comparion by _Feb 21_.
  - [x] :hourglass_flowing_sand: experiment on 3-SATs
  - [x] :traffic_light:  experiment on SAT-Race 2015 subsets
- [x] :package:  Packaging by _Feb. 22_.
  - [x] :clock1030: rebase on master branch
  - [x] :recycle: delete wip branches:
    - [x] noinline
    - [x] noinline-nowrap
    - [x] noinline-nowrap2
    - [x] nowrap
    - [ ] nowrap-with-inline
    - [x] reader
    - [x] validator
    - [x] wl3
    - [x] coredump
    - [x] 1.0.0-eval
    - [x] 1.0.2-eval
  - [x] cancel 1.0.1

**Comment by shnarazk** [comment]
memo1

```
$ sat-benchmark -3 250 -L 200 -s mios-WIP
# by sat-benchmark.hs 0.8.7 @ 2016-02-01T10:45:30+0900
# parameters: '' and timeout: 1000 sec.
solver, num, target, time
# mios WIP after 1.0.1
# designate: 3794408 2016-02-01T10:45 /home/narazaki/.local/bin/mios-WIP
"mios-WIP", 1, 200,      44.53
"mios-WIP", 2, 225,      145.04
"mios-WIP", 3, 250,      441.66
"mios-WIP", 4, "een",    5.68
"mios-WIP", 5, "bmc",    19.74
"mios-WIP", 6, "38b",    3.90
```

**Comment by shnarazk** [comment]
実行時間を測るのに real timeを使っていたことが判明！ だめじゃん :bangbang:  実験全部やり直し   :bangbang:  計画は2日ほど遅延 :bangbang:

**Comment by shnarazk** [comment]
#6 affects some data.  I need:
- [x] mios-WIP as bug fixed 1.0.1
- [x] mios-wl4
- [x] minisat-1.4 (user user time instead of real time)
- [ ] minisat-2.0 (use user time instead of real time)
- [ ] glucose /m mutlithread (real time is OK)

**Comment by shnarazk** [comment]
![screenshot from 2016-02-19 21-33-36](https://cloud.githubusercontent.com/assets/997855/13175862/c3025634-d750-11e5-83d9-f902ff9e24f6.png)
